#pragma once

#define COLOUR_PAIR_EDITOR          1
#define COLOUR_PAIR_TITLEBAR        2
#define COLOUR_PAIR_ALERT           3
#define COLOUR_PAIR_TABS            4
#define COLOUR_PAIR_ACTIVETAB       5
#define COLOUR_PAIR_COLUMNHIGHLIGHT 6
#define COLOUR_PAIR_LINEHIGHLIGHT   7
#define COLOUR_PAIR_RULERNUMBERS    8
#define COLOUR_PAIR_RULERCURRENT    9
#define COLOUR_PAIR_RULERLINE       10
